export const typeColors = {
	normal: "#BCBCAC",
	fighting: "#BC5442",
	flying: "#669AFF",
	poison: "#AB549A",
	ground: "#DEBC54",
	rock: "#BCAC66",
	bug: "#ABBC1C",
	ghost: "#6666BC",
	steel: "#ABACBC",
	fire: "#FF421C",
	water: "#2F9AFF",
	grass: "#78CD54",
	electric: "#FFCD30",
	psychic: "#FF549A",
	ice: "#78DEFF",
	dragon: "#7866EF",
	dark: "#785442",
	fairy: "#FFACFF",
	shadow: "#0E2E4C",
};

export const statName = [
	{ name: "HP", color: "#DF2140" },
	{ name: "ATK", color: "#FF994D" },
	{ name: "DEF", color: "#eecd3d" },
	{ name: "SpA", color: "#eecd3d" },
	{ name: "SpD", color: "#85DDFF" },
	{ name: "SPD", color: "#FB94A8" },
	{ name: "TOT", color: "#7195DC" },
];
