export const typeColors = {
  normal: "#BCBCAC",
  fighting: "#BC5442",
  flying: "#669AFF",
  poison: "#AB549A",
  ground: "#DEBC54",
  rock: "#BCAC66",
  bug: "#ABBC1C",
  ghost: "#6666BC",
  steel: "#ABACBC",
  fire: "#FF421C",
  water: "#2F9AFF",
  grass: "#78CD54",
  electric: "#FFCD30",
  psychic: "#FF549A",
  ice: "#78DEFF",
  dragon: "#7866EF",
  dark: "#785442",
  fairy: "#FFACFF",
  shadow: "#0E2E4C",
};

export const types = [
  { id: "1", type: "normal" },
  { id: "2", type: "fighting" },
  { id: "3", type: "flying" },
  { id: "4", type: "poison" },
  { id: "5", type: "ground" },
  { id: "6", type: "rock" },
  { id: "7", type: "bug" },
  { id: "8", type: "ghost" },
  { id: "9", type: "steel" },
  { id: "10", type: "fire" },
  { id: "11", type: "water" },
  { id: "12", type: "grass" },
  { id: "13", type: "electric" },
  { id: "14", type: "psychic" },
  { id: "15", type: "ice" },
  { id: "16", type: "dragon" },
  { id: "17", type: "dark" },
  { id: "18", type: "fairy" },
  { id: "19", type: "stellar" },
  { id: "10001", type: "unknown" },
];

export const statName = [
  { name: "HP", color: "#DF2140" },
  { name: "ATK", color: "#FF994D" },
  { name: "DEF", color: "#eecd3d" },
  { name: "SpA", color: "#eecd3d" },
  { name: "SpD", color: "#85DDFF" },
  { name: "SPD", color: "#FB94A8" },
  { name: "TOT", color: "#7195DC" },
];
